theme = "tokyo-night-day"

[palettes.tokyo-night-day]
base = "#dddde3"
fg = "#3760bf"
blue = "#2e7de9"
magenta = "#9854f1"
red = "#c41c46"
green = "#587539"
yellow = "#a27629"
cyan = "#007ea8"
surface1 = "#d0d5e3"
surface2 = "#b7c1e3"
surface3 = "#979fba"
surface4 = "#777c92"
surface5 = "#5c6172"
bg = "#dddde3"
cursor = "#3760bf"
cursor_text = "#ffffff"
selection = "#b7c1e3"
black = "#d0d5e3"
white = "#3760bf"
bright_black = "#777c92"

[palettes.tokyo-night]
base = "#181a27"
fg = "#c8d3f5"
blue = "#82aaff"
magenta = "#c099ff"
red = "#ff757f"
green = "#c3e88d"
yellow = "#ffc777"
cyan = "#86e1fc"
surface1 = "#212330"
surface2 = "#2f334d"
surface3 = "#3b4261"
surface4 = "#545c7e"
surface5 = "#727aac"
bg = "#212330"
cursor = "#c8d3f5"
cursor_text = "#181a27"
selection = "#2d3f76"
black = "#181a27"
white = "#c8d3f5"
bright_black = "#727aac"

[palettes.neovim-default]
base = "#14161b"
fg = "#e0e2ea"
blue = "#a6dbff"
magenta = "#ffcaff"
red = "#ffc0b9"
green = "#b3f6c0"
yellow = "#fce094"
cyan = "#8cf8f7"
surface1 = "#1b1e25"
surface2 = "#4f5258"
surface3 = "#4f5258"
surface4 = "#79839c"
surface5 = "#79839c"
bg = "#14161b"
cursor = "#e0e2ea"
cursor_text = "#14161b"
selection = "#4f5258"
black = "#1b1e25"
white = "#eef1f8"
bright_black = "#79839c"

[palettes.neovim-light]
base = "#e0e2ea"
fg = "#14161b"
blue = "#004c73"
magenta = "#470045"
red = "#590008"
green = "#005523"
yellow = "#6b5300"
cyan = "#007373"
surface1 = "#d7d8db"
surface2 = "#9b9ea4"
surface3 = "#9b9ea4"
surface4 = "#4f5258"
surface5 = "#4f5258"
bg = "#e0e2ea"
cursor = "#000000"
cursor_text = "#ffffff"
selection = "#9b9ea4"
black = "#07080d"
white = "#d7d8db"
bright_black = "#4f5258"

[palettes.carbonfox]
base = "#161616"
fg = "#f2f4f8"
blue = "#78a9ff"
magenta = "#be95ff"
red = "#ee5396"
green = "#25be6a"
yellow = "#08bdba"
cyan = "#33b1ff"
surface1 = "#282828"
surface2 = "#2a2a2a"
surface3 = "#535353"
surface4 = "#484848"
surface5 = "#6e6f70"
bg = "#161616"
cursor = "#f2f4f8"
cursor_text = "#161616"
selection = "#2a2a2a"
black = "#282828"
white = "#dfdfe0"
bright_black = "#484848"
