general {
    lock_cmd = "$HOME/.config/hypr/hyprlock-launch"
    before_sleep_cmd = "$HOME/.config/hypr/hyprlock-launch"
    after_sleep_cmd = niri msg action power-on-monitors
    inhibit_sleep = 2
}

listener {
    timeout = 120
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}

listener {
    timeout = 125
    on-timeout = "$HOME/.config/hypr/hyprlock-launch"
}

listener {
    timeout = 180
    on-timeout = systemctl suspend
}
