shell nu

#--- GENERAL ---#

include ./themes/neovim-default.conf
confirm_os_window_close 0
window_margin_width 0 2
enable_audio_bell no
dim_opacity 1.0

modify_font baseline 0
disable_ligatures always
text_composition_strategy platform

#--- FONTS ---#

# font_size 13
# modify_font cell_height +4
# modify_font underline_position 5
# modify_font underline_thickness 1
# font_family Input

font_size 13
modify_font cell_height +5
modify_font underline_position 2.2
modify_font underline_thickness 0.6
font_family Hermit

# font_size 13.5
# modify_font cell_height +5
# modify_font underline_position 2.2
# modify_font underline_thickness 0.6
# font_family CommitMono

# font_size 13
# modify_font cell_height +4
# font_family      Rec Mono Linear
# bold_font        Rec Mono Linear Bold
# italic_font      Rec Mono Casual Italic
# bold_italic_font Rec Mono Casual Bold Italic

# font_size 13
# modify_font cell_height +4
# modify_font underline_position 2.2
# modify_font underline_thickness 0.6
# font_family      Monaspace Neon
# bold_font        Monaspace Neon Bold
# italic_font      Monaspace Xenon
# bold_italic_font Monaspace Xenon Bold

#--- CURSOR ANIMATION ---#

cursor_trail 1
cursor_trail_decay 0.0001 0.2
cursor_trail_start_threshold 3

#--- KEYBINDS ---#
map ctrl+shift+j no_op
map ctrl+shift+k no_op
map ctrl+shift+l no_op
map ctrl+shift+h no_op

map super+ctrl+f send_text all \x1bf
map super+ctrl+b send_text all \x1bb

map super+backspace send_text all \x17
map alt+backspace   send_text all \x15

map super+h      send_text all \x1bh
map super+j      send_text all \x1bj
map super+k      send_text all \x1bk
map super+l      send_text all \x1bl

map alt+c        copy_to_clipboard
map alt+v        paste_from_clipboard
map alt+shift+comma load_config_file

#--- FONT CHARACTERS ---#
symbol_map U+274C,U+2714 Adwaita Mono
narrow_symbols U+274C 4
narrow_symbols U+2714 4

# All possible nerdfont unicodes
symbol_map U+e5fa-U+e6b5                                Symbols Nerd Font Mono
symbol_map U+e700-U+e7c5                                Symbols Nerd Font Mono
symbol_map U+ed00-U+f2ff                                Symbols Nerd Font Mono
symbol_map U+e200-U+e2a9                                Symbols Nerd Font Mono
symbol_map U+f0001-U+f1af0                              Symbols Nerd Font Mono
symbol_map U+e300-U+e3e3                                Symbols Nerd Font Mono
symbol_map U+f400-U+f533,U+2665,U+26A1                  Symbols Nerd Font Mono
symbol_map U+e0a0-U+e0a2,U+e0b0-U+e0b3                  Symbols Nerd Font Mono
symbol_map U+e0a3,U+e0b4-U+e0c8,U+e0ca,U+e0cc-U+e0d7    Symbols Nerd Font Mono
symbol_map U+23fb-U+23fe,U+2b58                         Symbols Nerd Font Mono
symbol_map U+f300-U+f375                                Symbols Nerd Font Mono
symbol_map U+e000-U+e00a                                Symbols Nerd Font Mono
symbol_map U+ea60-U+ec1e                                Symbols Nerd Font Mono
symbol_map U+276c-U+2771,U+2500-U+259f                  Symbols Nerd Font Mono
