shell "/run/current-system/sw/bin/nu"
include ./themes/tokyo-night-day.conf

window_margin_width 0 2
macos_option_as_alt yes
confirm_os_window_close 0
macos_traditional_fullscreen yes
hide_window_decorations titlebar-only

font_size 18
modify_font baseline 0
modify_font cell_height +8
modify_font underline_position 2

#--- KEYBINDS ---#
map ctrl+shift+j    no_op
map ctrl+shift+k    no_op
map ctrl+shift+l    no_op
map ctrl+shift+h    no_op
map alt+ctrl+f      send_text all \x1bf
map alt+ctrl+b      send_text all \x1bb
map alt+backspace   send_text all \x17
map super+backspace send_text all \x15
map shift+enter     send_text all \x1b[13;2u
map alt+h           send_text all \x1bh
map alt+j           send_text all \x1bj
map alt+k           send_text all \x1bk
map alt+l           send_text all \x1bl
map alt+c           copy_to_clipboard
map alt+v           paste_from_clipboard
map alt+shift+comma load_config_file

font_family Iosevka Custom
