shell "/run/current-system/sw/bin/nu"
include ./themes/neovim-default.conf

window_margin_width 0 2
macos_option_as_alt yes
confirm_os_window_close 0
macos_traditional_fullscreen yes
hide_window_decorations titlebar-only

font_size 18
modify_font baseline 0
modify_font cell_height +8
modify_font underline_position 2

font_family OCR-X TTF

map f5 load_config_file
