[general]
import = [ "~/.config/alacritty/themes/tokyo-night-day.toml" ]

[env]
TERM = "alacritty"

[terminal]
shell = "nu"

[cursor]
style = { blinking = "Never" }

[font]
size = 12.5
offset = { y = 9, x = 0 }
glyph_offset = { y = 3, x = 0 }

normal = { family = "MD IO Trial"}

# normal = { family = "Rec Mono Linear" }
# bold = { family = "Rec Mono Linear" }
# italic = { family = "Rec Mono Casual" }
# bold_italic = { family = "Rec Mono Casual" }

[window]
title = "Terminalino"
dynamic_padding = true

[window.padding]
x = 0
y = 0

[keyboard]
bindings = [
  { key = "V", mods = "Alt", action = "Paste" },
  { key = "C", mods = "Alt", action = "Copy" },

  { key = "F", mods = "Super|Control", chars = "\u001bf" },
  { key = "B", mods = "Super|Control", chars = "\u001bb" },

  { key = "Enter", mods = "Shift", chars = "\x1b[13;2u" },
  { key = "Backspace", mods = "Super", chars = "\u0017" },
  { key = "Backspace", mods = "Alt", chars = "\u0015" },

  { key = "H", mods = "Super", chars = "\u001Bh" },
  { key = "J", mods = "Super", chars = "\u001Bj" },
  { key = "K", mods = "Super", chars = "\u001Bk" },
  { key = "L", mods = "Super", chars = "\u001Bl" },
]
